Red Black tree Fixes
spbu-coding-2023/trees-1 pull request #6
Opened 2024-03-27 22:31 UTC by kinokotakenoko9

Fixes red black tree. now, checks for cases where null can occur
Besides that, improves style of code
and adds libs toml file (it should have been here before)

2024-03-28 00:36 UTC, Mukovenkov-Roman-Sergeyevich requested changes
Сори, что тебе пришлось делать, не нужно было так...

2024-03-28 00:36 UTC, Mukovenkov-Roman-Sergeyevich commented on lib/src/main/kotlin/bst/balancers/RedBlackTreeBalancer.kt
> +                if (grandparent != null) inserter(grandparent)
Иде ругается что деда может не быть? Только сверху объяснил почему дед существует. Дядю можешь оставить - верно (он кстати зависит от деда, тогда и дедус вообще в этом случае не может быть нулом). Про !! согласен.

2024-03-28 00:36 UTC, Mukovenkov-Roman-Sergeyevich commented on lib/src/main/kotlin/bst/RedBlackTree.kt
> +        val nodeToRemove = findNode(key) ?: return null
Ааа, понял. Надо не значение, а нодку искать. Думаю тогда и у обычного дерева должно быть то же самое. Хотел пройти этот момент потом, когда появятся базовые реализации бинарного

2024-03-28 00:36 UTC, Mukovenkov-Roman-Sergeyevich commented on lib/src/main/kotlin/bst/RedBlackTree.kt
> +
Я не очень понимаю как пользователь должен обращаться с этими setNode, что это ему даёт, если он вообще всё замещает собою? Как потом баланс восстанавливать? P.S. Вижу ответ, оказывается, это для разраба и просто фигня из за наследования - я припишу комментарий not functional

2024-03-28 00:36 UTC, Mukovenkov-Roman-Sergeyevich commented on lib/src/main/kotlin/bst/RedBlackTree.kt
> +                node.parent?.right = child
node.parent проверяется на null до этого. Иде просит "?" ?
Про child - он там может быть нулом! Сюда заходят в таких случаях : один чайлд не пустой или все чайлды пустые. Надо изменить в начале, что чайлд принимает тип RedBlackTreeNode<K, V>? .

2024-03-28 00:36 UTC, Mukovenkov-Roman-Sergeyevich commented on lib/src/main/kotlin/bst/RedBlackTree.kt
> +        replaceNodeAndChild(nodeToRemove, child!!)
Понял, что тут комментарий был misleading. child может быть нулём и это не error !!. И внизу тогда оставить ? .

2024-03-28 00:36 UTC, Mukovenkov-Roman-Sergeyevich commented on lib/src/main/kotlin/bst/RegularAbstractBSTWithBalancer.kt
> +    RegularAbstractBST<K, V, R>() {
👍

2024-03-28 00:36 UTC, Mukovenkov-Roman-Sergeyevich commented on lib/src/main/kotlin/bst/balancers/RedBlackTreeBalancer.kt
> +        val grandparent = this.findGrandparent() ?: return null
Согласен

2024-03-28 00:36 UTC, Mukovenkov-Roman-Sergeyevich commented on lib/src/main/kotlin/bst/balancers/RedBlackTreeBalancer.kt
>                  }
В результате ротейта по Википедии случаю инсёрта 4 гарантируется, что соответственные current left и right не нулы (на самом деле это будут current.parent которые ты так яростно защищаешь) ---> ?: return бесполезные

2024-03-28 00:36 UTC, Mukovenkov-Roman-Sergeyevich commented on lib/src/main/kotlin/bst/balancers/RedBlackTreeBalancer.kt
> +                grandparent?.setRed()
Тут так же гарантируется существование деда

2024-03-28 00:36 UTC, Mukovenkov-Roman-Sergeyevich commented on lib/src/main/kotlin/bst/balancers/RedBlackTreeBalancer.kt
> +            this.parent?.right -> return this.parent?.left
👍 Лишняя проверка тут нужна

2024-03-28 00:36 UTC, Mukovenkov-Roman-Sergeyevich commented on lib/src/main/kotlin/bst/balancers/RedBlackTreeBalancer.kt
> +                    rotateRight(node.parent!!)
Кстати, о !!, нам же говорили их избегать 🤓

2024-03-28 00:36 UTC, Mukovenkov-Roman-Sergeyevich commented on lib/src/main/kotlin/bst/balancers/RedBlackTreeBalancer.kt
> +            if (sibling != null && sibling.isRed()) {
По моему сиблинг там должен существовать, поставь тогда !! Посмотрим

2024-03-28 00:36 UTC, Mukovenkov-Roman-Sergeyevich commented on lib/src/main/kotlin/bst/balancers/RedBlackTreeBalancer.kt
>                      }
Короче говоря убери все ретурны и != null и поставь везде хардкорные !! 
Если огонь и вспыхнет, мы будем знать где его тушить
А то как будто оно вообще фигню сотворит если не найдёт брата своего

2024-03-28 12:05 UTC, kinokotakenoko9 commented on lib/src/main/kotlin/bst/RedBlackTree.kt
> +
это то как мы хотим обновлять поля узлов ( узлы разные бывают ). тут я написал дефолтное поведение, чтобы ошибки не было, я не думал про то как сохранять сбалансированность дерева ( т.к. каждый сам делает свое дерево )

2024-03-28 12:06 UTC, kinokotakenoko9 commented on lib/src/main/kotlin/bst/balancers/RedBlackTreeBalancer.kt
> +                if (grandparent != null) inserter(grandparent)
тип должен совпадать, пришлось так сделать ( хотя можно лучше )

2024-03-28 12:10 UTC, kinokotakenoko9 commented on lib/src/main/kotlin/bst/RedBlackTree.kt
> +        replaceNodeAndChild(nodeToRemove, child!!)
тип функции не совпадал, если то не так как ты хотел, то нужно поправить

2024-03-28 12:13 UTC, kinokotakenoko9 commented on lib/src/main/kotlin/bst/balancers/RedBlackTreeBalancer.kt
>                  }
current не должен быть null, return никогда не сработает, нужно было в current записать не null значение

2024-03-28 12:14 UTC, kinokotakenoko9 commented on lib/src/main/kotlin/bst/balancers/RedBlackTreeBalancer.kt
> +                grandparent?.setRed()
котлин не настолько умный. он в тупую тип сравнил и нашел ошибку, я исправил

2024-03-28 12:15 UTC, kinokotakenoko9 commented on lib/src/main/kotlin/bst/balancers/RedBlackTreeBalancer.kt
> +            if (sibling != null && sibling.isRed()) {
то же самое будет

2024-03-28 12:18 UTC, kinokotakenoko9 commented on lib/src/main/kotlin/bst/balancers/RedBlackTreeBalancer.kt
>                      }
это странно, в алгоритме должны эти случаи обрабатываться, а на этой строчки гарантировано не должно быть нулов, опять же, это можно сделать лучше выписав в отдельные переменные не нулл значения

2024-03-29 17:21 UTC, Mukovenkov-Roman-Sergeyevich commented on lib/src/main/kotlin/bst/balancers/RedBlackTreeBalancer.kt
> +            if (sibling != null && sibling.isRed()) {
Не то же самое... Одно хотя бы будет оповещать об ошибке.

2024-03-29 18:37 UTC, Mukovenkov-Roman-Sergeyevich approved these changes
I've restored red black's intended logic and added (regretfully) !! for debugging. Otherwise with checks for null we wouldn't know where the error was.

2024-03-29 18:44 UTC, merged